import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="8 August 2026">
      <p>
        Gwent Digital Ltd (&ldquo;we&rdquo;, &ldquo;us&rdquo;) is the data controller for
        information collected through gwentdigital.co.uk. This policy explains what we collect,
        why, and what rights you have under UK GDPR.
      </p>

      <h2>What we collect</h2>
      <p>When you use our contact form, we collect:</p>
      <ul>
        <li>Your name and email address</li>
        <li>Your business name and phone number, if you provide them</li>
        <li>The service you&rsquo;re enquiring about and your message</li>
        <li>Your budget range, if you choose to share it</li>
      </ul>
      <p>
        We don&rsquo;t use tracking cookies or collect analytics data on this site beyond basic,
        anonymous technical logs generated by our hosting provider (Vercel) to keep the site
        secure and running.
      </p>

      <h2>Why we collect it</h2>
      <p>
        We use this information solely to respond to your enquiry and, if you go ahead, to
        deliver the project you&rsquo;ve asked us to quote or build. The lawful basis is your
        consent (given when you tick the consent box on the form) and our legitimate interest in
        responding to enquiries sent to us.
      </p>

      <h2>How long we keep it</h2>
      <p>
        We keep enquiry emails for as long as reasonably needed to respond to you and, where a
        project goes ahead, for the duration of that relationship plus a reasonable period
        afterwards for accounting and legal purposes. We don&rsquo;t sell or share your details
        with third parties for marketing.
      </p>

      <h2>Your rights</h2>
      <p>Under UK GDPR, you have the right to:</p>
      <ul>
        <li>Ask what personal data we hold about you and get a copy of it</li>
        <li>Ask us to correct inaccurate data</li>
        <li>Ask us to delete your data</li>
        <li>Object to or restrict how we use your data</li>
        <li>Complain to the Information Commissioner&rsquo;s Office (ICO) if you&rsquo;re unhappy with how we&rsquo;ve handled your data</li>
      </ul>
      <p>
        To exercise any of these rights, email{" "}
        <a href="mailto:hello@gwentdigital.co.uk">hello@gwentdigital.co.uk</a>.
      </p>

      <h2>Third parties</h2>
      <p>
        We use Resend to send emails and Vercel to host this site. Both process data on our
        behalf under their own data processing terms; we don&rsquo;t give them permission to use
        your data for anything else.
      </p>
    </LegalPage>
  );
}
